import { library } from '@fortawesome/fontawesome-svg-core';
import { 
    faEthereum
 } from '@fortawesome/free-brands-svg-icons';

import { 
    faChartLine, 
    faTimes, 
    faPlusCircle, 
    faCoins, 
    faTag, 
    faUser, 
    faAddressCard, 
    faCartPlus,
    faSpinner,
    faCalendar,
    faCalendarPlus,
    faCalendarCheck,
    faClock,
    faEdit,
    faStickyNote,
    faWallet,
    faHome,
    faListAlt,
    faQuestionCircle,
    faInfoCircle,
    faParachuteBox,
    faUserTie,
    faSignal,
    faLifeRing,
    faMoneyBill,
    faCog,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faEthereum, 
    faChartLine, 
    faTimes, 
    faPlusCircle, 
    faCoins, 
    faTag, 
    faUser, 
    faAddressCard, 
    faCartPlus,
    faSpinner,
    faCalendar,
    faCalendarPlus,
    faCalendarCheck,
    faClock,
    faEdit,
    faStickyNote,
    faWallet,
    faHome,
    faListAlt,
    faQuestionCircle,
    faInfoCircle,
    faParachuteBox,
    faUserTie,
    faSignal,
    faLifeRing,
    faMoneyBill,
    faCog,
    );
