version: '2'
services:
  app-client:
    image: tuanlh2704/dapp-client:0.1
    ports:
      - 3000:3000
  app-api-server:
    image: tuanlh2704/dapp-server:0.1
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --requirepass 12345678 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - data:/data
volumes:
  data: